"""add role to users

Revision ID: 434a7fe9880d
Revises: 545fa23aada4
Create Date: 2026-01-28 13:51:56.319056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '434a7fe9880d'
down_revision: Union[str, Sequence[str], None] = '545fa23aada4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('stock', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('role', sa.String(), nullable=False, server_default="user"))
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_column('products', 'stock')
    # ### end Alembic commands ###
