"""Create all tables

Revision ID: d9993a5e8ee2
Revises: 2051da5d20f7
Create Date: 2026-02-03 15:39:24.618562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9993a5e8ee2'
down_revision: Union[str, Sequence[str], None] = '2051da5d20f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_avatar_images_user_id'), table_name='avatar_images')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_avatar_images_user_id'), 'avatar_images', ['user_id'], unique=False)
    # ### end Alembic commands ###
