"""mahsulotga_rang_qoshildi

Revision ID: e163c43a9511
Revises: 8b513cbc21c4
Create Date: 2026-02-07 11:11:25.140584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e163c43a9511'
down_revision: Union[str, Sequence[str], None] = '8b513cbc21c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('colour', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'colour')
    # ### end Alembic commands ###
